Repository game1n/t8-cms, pull requests merged in 2022-10, with the labels that each got.

#8 #5 eslint and prettier setup
  .eslintrc.js
  .husky/pre-commit
  .prettierignore
  .prettierrc.json
  package.json
  src/App.tsx
  src/components/LoginForm.tsx
  src/config/supabase.ts
  src/index.tsx
  src/navigation/NotFound.tsx
  src/navigation/RouterConfig.tsx
  src/navigation/index.ts
  src/screens/Home.tsx
  src/screens/Login.tsx
Labels: hacktoberfest-accepted

#16 Add README.md
  README.md
Labels: hacktoberfest-accepted

#17 chore: add pull request template md file
  .github/pull_request_template.md
Labels: hacktoberfest-accepted

#22 21 fix eslint issues/refactoring
  .eslintrc.js
  src/components/LoginForm.tsx
  src/constants/login.constants.ts
  src/constants/supabase.constants.ts
  src/enums/login.enums.ts
  src/enums/storage.enums.ts
  src/models/login.models.ts
  src/models/storage.models.ts
  src/models/supabase.models.ts
  src/navigation/RouterConfig.tsx
  src/screens/Login.tsx
  src/services/auth.ts
  src/services/login.service.ts
  src/services/storage.service.ts
  src/services/supabase.service.ts
Labels: hacktoberfest-accepted

#25 fix modal close
  src/components/BlogForm.tsx
  src/components/BlogSection.tsx
  src/models/blog.models.ts
  src/screens/Home.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#19 15 shared Loaded based on MUI
  src/components/loader.tsx
Labels: hacktoberfest-accepted

#27 [Feature] - Issue 26 : added onboarding and blogs opening flow
  src/components/BlogCard.tsx
  src/components/BlogForm.tsx
  src/components/BlogSection.tsx
  src/components/Header.tsx
  src/components/OnboardingForm.tsx
  src/constants/blog.constants.ts
  src/constants/onboarding.constants.ts
  src/constants/user.constants.ts
  src/models/blog.models.ts
  src/models/header.models.ts
  src/models/onboarding.models.ts
  src/models/user.models.ts
  src/screens/Home.tsx
  src/services/auth.ts
  src/services/user.ts
Labels: hacktoberfest-accepted

#45 [Feature] - issue 43
  src/App.tsx
  src/components/BlogForm.tsx
  src/components/BlogSection.tsx
  src/components/Header.tsx
  src/components/MarkdownPost.tsx
  src/index.css
  src/models/blog.models.ts
  src/models/header.models.ts
  src/navigation/RouterConfig.tsx
  src/navigation/index.ts
  src/reducers/user/action.ts
  src/reducers/user/reducer.ts
  src/screens/Home.tsx
  src/screens/Publish.tsx
  src/store/userContext.tsx
Labels: hacktoberfest
